### PR TITLE
Only create a `_16` file when there are negative certs

### PR DESCRIPTION
**Pull request by pete-woods**
Otherwise you end up with an empty `rootcerts_16.go` file, and the compiler / linters do not like it.

### CODE REVIEW

**Comment by pete-woods** [comment]
@gwatts please let me know what I can do to help get this merged 🙇

**Comment by gwatts** [comment]
@pete-woods Go 1.6 is "ancient" at this point; i think i'd just remove support for it completely and stop generating that file, if you feel like adjusting the PR to achieve that :-)

**Comment by gwatts** [comment]
Removed support for Go <1.6 as of 873fe3267079d32ed2a06f728fa840a608355e7d

**Comment by pete-woods** [comment]
Brilliant, thanks for doing that. Had planned to circle round but kept finding myself too busy.

**Pull request closed without merging**
